[project]
name = "pinmeto-mcp-spike"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "black>=25.1.0",
    "dotenv>=0.9.9",
    "httpx>=0.28.1",
    "mcp[cli]>=1.13.1",
]
