#!/usr/bin/env node
/**
 * Writes src/generated/version.ts from package.json.
 *
 * The server needs its own name and version at runtime for serverInfo and the
 * User-Agent. Reading package.json at runtime ties the entry point to a fixed
 * position on disk, which breaks single-file bundling. Generating a module keeps
 * package.json as the one source of truth while working under tsc, esbuild, and
 * Vitest alike.
 */

import { readFileSync, writeFileSync, mkdirSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const rootDir = join(dirname(fileURLToPath(import.meta.url)), '..');
const pkg = JSON.parse(readFileSync(join(rootDir, 'package.json'), 'utf-8'));
const outDir = join(rootDir, 'src', 'generated');

mkdirSync(outDir, { recursive: true });
writeFileSync(
  join(outDir, 'version.ts'),
  `// Generated by scripts/generate-version.js. Do not edit.\n` +
    `export const PACKAGE_NAME = ${JSON.stringify(pkg.name)};\n` +
    `export const PACKAGE_VERSION = ${JSON.stringify(pkg.version)};\n`
);

console.log(`Generated src/generated/version.ts (${pkg.name}@${pkg.version})`);
