name: Build MCP Desktop Extension

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm install
      - run: npm run build
      - name: Install dependencies
        run: |
          npm install
          npm run build
          npm ci
          npm i @anthropic-ai/mcpb -g
      - name: Test
        run: npm run test
      - name: Build MCP Desktop Extension
        run: |
          npm install
          npm run build
          npm ci --production
          rm manifest.js
          mcpb pack
      - name: Upload mcpb file
        uses: actions/upload-artifact@v4
        with:
          name: pinmeto-mcp
          path: pinmeto-location-mcp.mcpb
